services:
  client:
    restart: always
    build:
      args:
        VITE_BASE_URL: "http://localhost:8080/"
        VITE_API_BASE_URL: "http://goatless-api.goatlessband.com" # no trailing "/"
        VITE_LEGAL_ADDRESS: "Human Name<br>Humanstr. 42<br>12345 Human City<br>Germany"
        VITE_LEGAL_PHONE: "+49 123 4567890"
        VITE_LEGAL_EMAIL: "human.name@example.com"
        VITE_FOOTER_GITHUB_LINK: "https://github.com/amonbenson/goatless-website/"
        VITE_KNOWN_COUNTRIES: "germany,deutschland"
    ports:
      - "8080:80"
