services:
  client:
    restart: always
    build:
      args:
        VITE_BASE_URL: "http://localhost:8080/"
        VITE_API_BASE_URL: "http://goatless-api.goatlessband.com" # note: no trailing "/"
    ports:
      - "8080:80"
