services:
  frontend:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/app/dist
    environment:
      - NODE_ENV=production
      - VITE_PUBLIC_SERVER=${PUBLIC_SERVER_URL}

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # host:container
    environment:
      - PORT=5000
      - NODE_ENV=production
      - PUBLIC_SERVER=${PUBLIC_SERVER_URL}

  webhook:
    restart: always
    build:
      context: ./webhook
      dockerfile: Dockerfile
    ports:
      - "7000:7000" # host:container
    volumes:
      - ${WEBHOOK_PIPE}:/app/webhook.pipe
    environment:
      - PORT=7000
      - NODE_ENV=production
      - PUBLIC_SERVER=${PUBLIC_SERVER_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - WEBHOOK_PIPE=/app/webhook.pipe

  nginx:
    restart: always
    image: nginx:stable-alpine-slim
    ports:
      - "${PORT}:80" # host:container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/var/www/html:ro
    depends_on:
      - frontend
      - backend
      - webhook

volumes:
  frontend_dist:
