name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

  deploy:
    needs: lint

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup SSH key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H goatlessband.com >> ~/.ssh/known_hosts

      - name: Push to dokku server
        run: |
          git remote add dokku dokku@goatlessband.com:goatless-website
          git push dokku main --force
